# Generated by Django 5.1.4 on 2024-12-15 22:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("base_quantity", models.FloatField()),
                ("quantity", models.FloatField(blank=True, null=True)),
                ("unit", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=100)),
                ("difficulty", models.CharField(max_length=50)),
                ("prep_time", models.CharField(max_length=50)),
                ("cooking_time", models.CharField(max_length=50)),
                ("base_servings", models.IntegerField()),
                ("current_servings", models.IntegerField()),
                ("pre_prep_instructions", models.TextField()),
                ("instructions", models.TextField()),
                ("notes", models.TextField(blank=True)),
                (
                    "ingredients",
                    models.ManyToManyField(
                        related_name="recipes", to="recipes.ingredient"
                    ),
                ),
            ],
        ),
    ]
