# Generated by Django 5.1.4 on 2024-12-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="instructions",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="notes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="pre_prep_instructions",
            field=models.JSONField(),
        ),
    ]
